image Lokost normal = 'Lokost/Novel1-1.png'
image Lokost normal2 = 'Lokost/Novel2-4.png'
image Lokost normal3 = 'Lokost/Novel3-2.png'
image Lokost serio = 'Lokost/Novel1-5.png'
image Lokost serio2 = 'Lokost/Novel2-2.png'
image Lokost serio3 = 'Lokost/Novel4-3.png'
